security:
    password_hashers:
        # Spécifiez l'algorithme de hachage pour les mots de passe des utilisateurs
        App\Entity\UserAccount:
            algorithm: bcrypt

    # Fournisseur d'utilisateurs depuis la base de données
    providers:
        database_users:
            entity:
                class: App\Entity\UserAccount
                property: username

    firewalls:
        # Paramètres de la page de connexion
        main:
            provider: database_users
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: app_home # Redirige après une connexion réussie
            logout:
                path: app_logout

    access_control:
        # Contrôle d'accès : seuls les utilisateurs authentifiés peuvent accéder à certaines pages
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/shooping, roles: ROLE_USER }
        - { path: ^/shooping, roles: ROLE_ADMIN }
